import "./globals.css";
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({
  variable: '--font-dmSans',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} font-dmSans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
